[package]
name = "swarm-deployer"
version = "0.1.0"
authors = ["Quest <quest@lysator.liu.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bollard = { git = "https://github.com/iyzana/bollard", branch = "services-support" }
bollard = { path = "../../external/bollard" }
log = "*"
rusoto_core = "*"
rusoto_sqs = "*"
serde_json = "*"
snafu = "*"
stderrlog = "*"
structopt = "*"
tokio = "*"
