on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: check
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: bittrance/swarm-ecr-deployer
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
